version: '3.8'

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot
    env_file:
      - .env
    # run sh to persist after deployment
    command: /home/vscode/.local/bin/poetry run python -m deliverybot.bot
    depends_on:
      - server
    volumes:
      - ./deliverybot:/home/vscode/deliverybot/deliverybot
    tty: true  # persist (should use 'sh' as entrypoint)

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    command: /home/vscode/.local/bin/poetry run gunicorn --bind 0.0.0.0:5000 deliverybot.server.app:app
    volumes:
      - ./deliverybot/server:/home/vscode/deliverybot/deliverybot/server
    ports:
      - 5000:5000

